### ISSUE TITLE
A correct way to build tensorflow-sycl?

### ISSUE THREAD

**Issue by ghostplant** [codeplaysoftware/tensorflow#20]
Hi, I tries many possible cases to build tensorflow-sycl but all failed for compiling errors like `error: no template named 'map_allocator' in namespace 'cl::sycl'`

Can you provide the specific way to build it:

- tensorflow version: e.g. r1.6?
- bazel version: e.g. 0.5.4?
- build config options for sycl: e.g. `--config=-std=c++14`?
- compiler option: e.g. is standard gcc-5 ok?

Thanks!

**Comment by DuncanMcBain** [comment]
Hi @ghostplant, you should try to use the "eigen_sycl" branch of the repository, as this is the most up-to-date branch. GCC 5 should be perfectly acceptable along with a recent version of ComputeCpp (the map allocator hasn't existed in ComputeCpp for a long time, so any references to it are part of rather old code).

https://github.com/lukeiwanski/tensorflow/issues/256#issuecomment-420577008 has relevant information, I don't believe too much has changed in the last few months.

**Comment by ghostplant** [comment]
@DuncanMcBain Thank you, I used the branch you said and fixed an unsafe https problem when downloading some eigen-sycl dependencies and now the build is continuing!

**Comment by ghostplant** [comment]
@DuncanMcBain 

After the installation, and run some simple examples like mnist_cnn.py, and got the following error:
```sh
d to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2018-12-25 22:25:44.698423: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:70] Found following OpenCL devices:
2018-12-25 22:25:44.698462: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:72] id: 0, type: GPU, name: Tesla V100-PCIE-32GB, vendor: NVIDIA Corporation, profile: FULL_PROFILE
terminate called after throwing an instance of 'cl::sycl::compile_program_error'
Aborted (core dumped)
```

If I run a small example using OpenCL emulator such as oclgrind, the application would finish correctly.
The tensorflow-sycl is compiled with bitcode = `spir64`, is it the error root cause for NVIDIA OpenCL? (available bitcodes: spir spir64 spir32 spirv spirv64 spirv32 aorta-x86_64 ptx64 amdgcn)

**Comment by ghostplant** [comment]
I recompile the tensorflow-sycl with ptx64 bitcode, some basic apps like matrix_multiple can run correctly this time, but simple CNN applications still crash with `cl::sycl::compile_program_error'` ..

**Comment by DuncanMcBain** [comment]
PTX isn't as well supported in ComputeCpp as spir at the moment. I would say it is expected that quite a lot of code won't work (the main issue would be the presence of built-in functions, like `pow`, `sqrt` and so on - matmul is unlikely to use them so works).

**Comment by ghostplant** [comment]
So no solution for OpenCL from NV card?
And would it suport AMD/FPGA well?

**Comment by DuncanMcBain** [comment]
Some people have had success using [pocl](http://portablecl.org/), as it can target nvidia GPUs. I tried it at work, I didn't succeed and I can't try 'til I'm back. If you wanted to target pocl, you should compile to spir64.

We used to be able to run spir on AMD reliably a few years ago, but AMD deprecated support for it, so support is now patchy in their drivers. I don't know which driver version to recommend now and it is possible that a new enough GPU won't run spir at all (though we hope to be able to target their GPUs soon).

**Comment by Rbiessy** [comment]
Hi @ghostplant, it is as @DuncanMcBain said. One more precision concerning AMD support, we support the amdgpu-pro package version 17.50-511655 as mentioned here: https://developer.codeplay.com/computecppce/latest/getting-started-with-tensorflow

**Comment by ghostplant** [comment]
@Rbiessy Thanks, I will try it as long as I have an AMD card.

BTW, since specific bit-code is not supporting well for many accelerators, is it possible not to force to compile kernels into bit-codes and build them from source during runtime?

**Comment by Rbiessy** [comment]
Ok, great.
That would mean generating OpenCL C source from C++ which I know is not supported as of today. I don't know if it is a planned feature.

**Comment by ghostplant** [comment]
@Rbiessy So can ComputeCpp compiler compile most CUDA kernel source `kernel<<<...>>>(...)` into OpenCL bit-code ?

**Comment by Rbiessy** [comment]
SYCL compiles standard C++ so the main logic of the kernel would compile but CUDA-specific keywords such as `__global__` would need to be dropped, `__syncthreads` would be replaced by something else, etc.
Launching a kernel would also be different as triple chevron is not standard C++.
If you want to know more, there is a guide explaining these differences here: https://developer.codeplay.com/computecppce/latest/sycl-for-cuda-developers
Hope this helps!

**Comment by ghostplant** [comment]
@Rbiessy Thanks!

**Comment by Rbiessy** [comment]
Np :)
I'm closing this issue. If you have trouble with the instructions please create a specific issue.
