### ISSUE TITLE
What is CodePlay's plan to update TF SYCL integration to the latest TensorFlow version

### ISSUE THREAD

**Issue by shengfuintel** [codeplaysoftware/tensorflow#21]
I am working on using TensorFlow SYCL device to support my GPU. What is CodePlay's plan to update TF SYCL integration to the latest TensorFlow version?

**Comment by rodburns** [comment]
We are right now focusing on two priorities: Upstreaming Eigen and improving performance with the use of SYCL-DNN and SYCL-BLAS. These two jobs will then make it much easier to update TensorFlow in the future as well as much easier to optimize for different devices. If you want to contribute to the project, then doing the merge from upstream TensorFlow will be very much appreciated and help all of us a lot. We'd be happy to accept a merge request for this work.

**Comment by wangliwei-intel** [comment]
@rodburns Does it means if I want to try Tensorflow SYCL, I have to get tensorflow source from here and
the upstream Tensorflow (https://github.com/tensorflow/tensorflow) doesn't support SYCL so far?
Thank you.

**Comment by rodburns** [comment]
@wangliwei-intel Yes this is broadly correct. If you want to use the SYCL TensorFlow implementation you need to follow the instructions here that specify what branches, changelists and versions to use. https://developer.codeplay.com/products/computecpp/ce/guides/tensorflow-guide/tensorflow-amd-setup
We do plan to upstream the changes but first we are upstreaming the Eigen work we have done to that project.

**Comment by wangliwei-intel** [comment]
@rodburns 
Actually, I'm trying that pull request of Eigen, but I can't find the source code of benchmarks, and I've
raised the question there, do you know what the answer is?
https://bitbucket.org/eigen/eigen/pull-requests/442/enabling-optimised-eigen-sycl-backend-for/activity

Thank you!

**Comment by mirh** [comment]
Any update?
It would be cool if you could hit at least 1.12, so that it would be usable with python 3.7.

**Comment by rodburns** [comment]
As TensorFlow 2.0 will be released soon, we are assessing if we can migrate directly to that version and hopefully we can provide an update on that in due course

**Comment by Rbiessy** [comment]
Issue was answered so closing.

**Comment by tripzero** [comment]
@rodburns, what is the new status? It looks like eigen sycl PRs are merged. Is it possible to use upstream tensorflow (1.2.0 now) with the sycl build instructions?

**Comment by mirh** [comment]
Uh, by the way, I have it running with latest gcc and python here
https://aur.archlinux.org/pkgbase/tensorflow-computecpp/

I couldn't test it yet though.

**Comment by tripzero** [comment]
@mirh meaning python 3.7?

**Comment by rodburns** [comment]
@tripzero The Eigen work has been upstreamed to the main branch now but our TF branch should still be used. You can follow the latest instructions [here ](https://developer.codeplay.com/products/computecpp/ce/guides/tensorflow-guide/tensorflow-generic-setup)
