### ISSUE TITLE
Mobilenet-SSD operation not supported

### ISSUE THREAD

**Issue by foromer4** [codeplaysoftware/tensorflow#22]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
LInux Ubuntu 16.04 AARCH64 on Hikey960 
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.9
- **Python version**: 
3.6
- **Bazel version (if compiling from source)**:
1.6
- **GPU model and memory**:
MALI G71
- **Exact command to reproduce**:
Run Mobilenet SSD model

### Describe the problem
I am trying to run Mobilenet SSD and get this error:
```
I ./tensorflow/core/common_runtime/sycl/sycl_device.h:72] id: 0, type: GPU, name: Mali-G71, vendor: ARM, profile: FULL_PROFILE
starting loopsingle_detector_main_thread
terminate called after throwing an instance of 'cl::sycl::feature_not_supported'
Aborted
```
Any idea which operations are not supported? Are they planned to be added?
thanks,Omer

**Comment by Rbiessy** [comment]
Hello,
This is not an error due to a missing operations. Mobilenet SSD should definitely be working on ARM.

I think this may actually be an issue with this version of ComputeCpp. Can you update to CE 1.0.5? If you do so make sure to update to the latest version of the eigen_sycl branch.

I'm sorry you'll have to recompile everything again but please let me know if it works.

**Comment by foromer4** [comment]
@Rbiessy  thank you, but unfortunately still no go. I rebuilt latest eigen_sycl with CE 1.0.5 , and deployed both to hikey , I still get the same issue. We are able to run armcl on the same device with opencl so that indicates that opencl and MALI drivers are installed properly.

**Comment by rodburns** [comment]
@foromer4 Can you confirm where you got the Mali drivers from? The currently published public version are not working properly with SPIR-V. This is mentioned in the instructions:

Please contact Arm to obtain an Arm Mali driver with support for OpenCL 1.2 with SPIR-V.
Note that, as of the date of publication, the publicly released Arm Mali drivers available at https://developer.arm.com/products/software/mali-drivers/user-space do not correctly support SPIR-V.

**Comment by foromer4** [comment]
[here](https://developer.arm.com/products/software/mali-drivers/bifrost-kernel) is where we got the drivers from , following [this](https://github.com/96boards/documentation/blob/master/consumer/hikey/hikey960/guides/openCL-support.md) tutorial.

**Comment by rodburns** [comment]
Ok great. What is the output of computecpp_info and clinfo? computecpp_info is located in the bin folder of the ComputeCpp release.

**Comment by foromer4** [comment]
clinfo:

> Number of platforms                               1
>   Platform Name                                   ARM Platform
>   Platform Vendor                                 ARM
>   Platform Version                                OpenCL 2.0 v1.r9p0-01rel0.37c12a13c46b4c2d9d736e0d5ace2e5e
>   Platform Profile                                FULL_PROFILE
>   Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_il_program cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory cl_arm_shared_virtual_memory
>   Platform Extensions function suffix             ARM
> 
>   Platform Name                                   ARM Platform
> Number of devices                                 1
>   Device Name                                     Mali-G71
>   Device Vendor                                   ARM
>   Device Vendor ID                                0x60a00002
>   Device Version                                  OpenCL 2.0 v1.r9p0-01rel0.37c12a13c46b4c2d9d736e0d5ace2e5e
>   Driver Version                                  2.0
>   Device OpenCL C Version                         OpenCL C 2.0 v1.r9p0-01rel0.37c12a13c46b4c2d9d736e0d5ace2e5e
>   Device Type                                     GPU
>   Device Profile                                  FULL_PROFILE
>   Max compute units                               8
>   Max clock frequency                             5MHz
>   Device Partition                                (core)
>     Max number of sub-devices                     0
>     Supported partition types                     None
>   Max work item dimensions                        3
>   Max work item sizes                             256x256x256
>   Max work group size                             384
>   Preferred work group size multiple              4
>   Preferred / native vector sizes                 
>     char                                                16 / 16      
>     short                                                8 / 8       
>     int                                                  4 / 4       
>     long                                                 2 / 2       
>     half                                                 8 / 8        (cl_khr_fp16)
>     float                                                4 / 4       
>     double                                               0 / 0        (n/a)
>   Half-precision Floating-point support           (cl_khr_fp16)
>     Denormals                                     Yes
>     Infinity and NANs                             Yes
>     Round to nearest                              Yes
>     Round to zero                                 Yes
>     Round to infinity                             Yes
>     IEEE754-2008 fused multiply-add               Yes
>     Support is emulated in software               No
>     Correctly-rounded divide and sqrt operations  No
>   Single-precision Floating-point support         (core)
>     Denormals                                     Yes
>     Infinity and NANs                             Yes
>     Round to nearest                              Yes
>     Round to zero                                 Yes
>     Round to infinity                             Yes
>     IEEE754-2008 fused multiply-add               Yes
>     Support is emulated in software               No
>     Correctly-rounded divide and sqrt operations  No
>   Double-precision Floating-point support         (n/a)
>   Address bits                                    64, Little-Endian
>   Global memory size                              4080349184 (3.8GiB)
>   Error Correction support                        No
>   Max memory allocation                           1020087296 (972.8MiB)
>   Unified memory for Host and Device              Yes
>   Shared Virtual Memory (SVM) capabilities        (core)
>     Coarse-grained buffer sharing                 Yes
>     Fine-grained buffer sharing                   No
>     Fine-grained system sharing                   No
>     Atomics                                       No
>   Minimum alignment for any data type             128 bytes
>   Alignment of base address                       1024 bits (128 bytes)
>   Preferred alignment for atomics                 
>     SVM                                           0 bytes
>     Global                                        0 bytes
>     Local                                         0 bytes
>   Max size for global variable                    65536 (64KiB)
>   Preferred total size of global vars             0
>   Global Memory cache type                        Read/Write
>   Global Memory cache size                        524288
>   Global Memory cache line                        64 bytes
>   Image support                                   Yes
>     Max number of samplers per kernel             16
>     Max size for 1D images from buffer            65536 pixels
>     Max 1D or 2D image array size                 2048 images
>     Base address alignment for 2D image buffers   32 bytes
>     Pitch alignment for 2D image buffers          64 bytes
>     Max 2D image size                             32768x32768 pixels
>     Max 3D image size                             32768x32768x32768 pixels
>     Max number of read image args                 128
>     Max number of write image args                64
>     Max number of read/write image args           64
>   Max number of pipe args                         16
>   Max active pipe reservations                    1
>   Max pipe packet size                            1024
>   Local memory type                               Global
>   Local memory size                               32768 (32KiB)
>   Max constant buffer size                        65536 (64KiB)
>   Max number of constant args                     8
>   Max size of kernel argument                     1024
>   Queue properties (on host)                      
>     Out-of-order execution                        Yes
>     Profiling                                     Yes
>   Queue properties (on device)                    
>     Out-of-order execution                        Yes
>     Profiling                                     Yes
>     Preferred size                                2097152 (2MiB)
>     Max size                                      16777216 (16MiB)
>   Max queues on device                            1
>   Max events on device                            1024
>   Prefer user sync for interop                    No
>   Profiling timer resolution                      1000ns
>   Execution capabilities                          
>     Run OpenCL kernels                            Yes
>     Run native kernels                            No
>   printf() buffer size                            1048576 (1024KiB)
>   Built-in kernels                                
>   Device Available                                Yes
>   Compiler Available                              Yes
>   Linker Available                                Yes
>   Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_il_program cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory cl_arm_shared_virtual_memory
> 
> NULL platform behavior
>   clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  ARM Platform
>   clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [ARM]
>   clCreateContext(NULL, ...) [default]            Success [ARM]
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
>     Platform Name                                 ARM Platform
>     Device Name                                   Mali-G71
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
>     Platform Name                                 ARM Platform
>     Device Name                                   Mali-G71
> 
> ICD loader properties
>   ICD loader Name                                 OpenCL ICD Loader
>   ICD loader Vendor                               OCL Icd free software
>   ICD loader Version                              2.2.11
>   ICD loader Profile                              OpenCL 2.1

computecpp_info:

> ComputeCpp Info (CE 1.0.5)
> 
> SYCL 1.2.1 revision 3
> 
> ********************************************************************************
> 
> Toolchain information:
> 
> GLIBC version: 2.24
> GLIBCXX: 20160609
> This version of libstdc++ is supported.
> 
> ********************************************************************************
> 
> 
> Device Info:
> 
> Discovered 1 devices matching:
>   platform    : <any>
>   device type : <any>
> 
> --------------------------------------------------------------------------------
> Device 0:
> 
>   Device is supported                     : NO - Device does not support SPIR
>   CL_DEVICE_NAME                          : Mali-G71
>   CL_DEVICE_VENDOR                        : ARM
>   CL_DRIVER_VERSION                       : 2.0
>   CL_DEVICE_TYPE                          : CL_DEVICE_TYPE_GPU
> 
> If you encounter problems when using any of these OpenCL devices, please consult
> this website for known issues:
> https://computecpp.codeplay.com/releases/v1.0.5/platform-support-notes

**Comment by foromer4** [comment]
@Rbiessy , My ComputeCPP path in hikey is different than the path I used on my host computer when I built tensorflow. Might it cause this failure? just a guess....

**Comment by Rbiessy** [comment]
No that is not an issue. The only reason I can think of is the driver version I'm afraid.

**Comment by Rbiessy** [comment]
Issue was answered so closing.
