### ISSUE TITLE
'cl::sycl::compile_program_error' on Nvidia GPU

### ISSUE THREAD

**Issue by eslambakr** [codeplaysoftware/tensorflow#25]
Hello,
Thanks for this great effort.
I tried to install it on Ubuntu 16.04 on Nvidia GPU(GTX 1080 TI) using bit code PTX64.
I followed the installation steps as mentioned in [https://developer.codeplay.com/products/computecpp/ce/guides/tensorflow-guide/tensorflow-generic-setup](url)

But unfortunately,I faced the following error 
`terminate called after throwing an instance of 'cl::sycl::compile_program_error`
 while running a simple code 
`sess.run(tf.global_variables_initializer())` 

I think it is related to #20 but no clear solution is provided, and the documentation mentioned using ptx64 for Nvidia GPUs.

Thanks in advance.

**Comment by rodburns** [comment]
Hello,
At the moment we do not provide support for our TensorFlow branch on NVidia hardware. I think this is failing because we have not yet implemented all the OpenCL built-ins for ptx. Our ptx support with ComputeCpp is currently in an experimental status.
Thanks,
Rod.

**Comment by eslambakr** [comment]
Thanks @rodburns ,what about Imagination GPUs?

**Comment by rodburns** [comment]
We don't support PowerVR at the moment, but ComputeCpp and TensorFlow will work on a subset of PowerVR GPUs when Imagination release compatible OpenCL drivers in future. We are not sure exactly when that will be, but they are working on it: https://www.imgtec.com/blog/separating-the-wheat-from-the-chaff-in-embedded-ai/

**Comment by eslambakr** [comment]
@rodburns Thank you very much for your fast response.
I read the link above and after searching I found that in 13 June there is a new release [https://www.imgtec.com/blog/powervr-sdk-2019-release-1-now-available-for-download/](url)
[https://www.imgtec.com/developers/powervr-sdk-tools/whats-new/](url)
which contain support for SPIR-V as I think but I am not sure

As said in the release notes:
`Integrated glslang into our SDK as a cmake external project, so you can use runtime generation of SPIR-V modules. Our Vulkan PostProcessing example now takes advantage of this to runtime-generate shaders.`

Does this mean, they are supporting SPIR-V currently?or I misunderstood that?
Thanks.

**Comment by rodburns** [comment]
Hi,
We're going to ask Imagination Technologies what support is provided in that version, or if you will need to wait for a new version.
What are you planning on running? Is there a particular model you are trying to use?
Rod.

**Comment by eslambakr** [comment]
1- I am trying to build Tensorflow on my board which contains PowerVR Series 6XT GX6250, It is mentioned in this guide [https://developer.codeplay.com/products/computecpp/ce/guides/tensorflow-guide/tensorflow-arm-setup](url) that I need opencl with supported SPIR-V to be able to build and run it correctly, As I see there isn't a supported SDK from Imagination Technologies till 13 JUNE 2019 for SPIR-V but in this release I think it becomes supported [https://www.imgtec.com/blog/powervr-sdk-2019-release-1-now-available-for-download/](url) as mentioned in the release notes, but I can't guarantee that so I want to make sure from you :smiley: 

2- Regarding your question, there isn't a particular model I want to run, I want to inference only any simple model using the opencl to be able to run on the GPU instead of CPU, let's say a simple binary classifier (e.g, 2 CNN + one fully connected).

Thanks.

**Comment by rodburns** [comment]
We don't know whether that published driver will work but you can try it out.

At the moment it's best to use SPIR rather than SPIR-V, I'll try to provide some specific instructions for PowerVR here to try out.

We don't have specific instructions for PowerVR currently, but you can try using the ARM instructions with some modifications:

** export TF_SYCL_BITCODE_TARGET=spir64 (Note: this is changed from spirv64)
** The final bazel command should look like this: 
bazel --output_user_root=$TMPDIR build --config=sycl_arm -c opt --verbose_failures -DEIGEN_SYCL_LOCAL_THREAD_DIM0=8 -DEIGEN_SYCL_LOCAL_THREAD_DIM1=8 -DEIGEN_SYCL_ASYNC_EXECUTION=1 --copt=-Wno-c++11-narrowing //tensorflow/tools/pip_package:build_pip_package

**Comment by eslambakr** [comment]
Regarding ARM instructions when I ran the following command as mentioned 

> bazel --output_user_root=$TMPDIR build --config=sycl_arm -c opt --verbose_failures --copt=-DEIGEN_DONT_VECTORIZE_SYCL --copt=-Wno-c++11-narrowing //tensorflow/tools/pip_package:build_pip_package

I got this
`ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'sycl/build_defs.bzl': no such package '@local_config_sycl//sycl'`

After trying your modifications I got 
`ERROR: Invalid options syntax: -DEIGEN_SYCL_LOCAL_THREAD_DIM0=8`

Thanks for your support and quick reply :heart:

**Comment by rodburns** [comment]
For the first error message, it looks like you might not have followed all the instructions correctly. I'd suggest cleaning the cache with rm -rf $TMPDIR and making sure all the environment variables are exported before running ./configure. 
If you post the contents of the .tf_configure.bazelrc file generated after running ./configure

For the second error message, the bazel command is missing some --copt, the full command is:
Romain Biessy: Hi, regarding https://github.com/codeplaysoftware/tensorflow/issues/25#issuecomment-537497603
For the first error message, some instructions were not followed properly. I'd suggest cleaning the cache with rm -rf $TMPDIR and making sure all the environment variables are exported before running ./configure. We may be able to help more if they post the content of the .tf_configure.bazelrc file generated after running ./configure

For the second error message, the bazel command is missing some --copt, the full command is:

bazel --output_user_root=$TMPDIR build --config=sycl_arm -c opt --verbose_failures --copt=-DEIGEN_SYCL_LOCAL_THREAD_DIM0=8 --copt=-DEIGEN_SYCL_LOCAL_THREAD_DIM1=8 --copt=-DEIGEN_SYCL_ASYNC_EXECUTION=1 --copt=-Wno-c++11-narrowing //tensorflow/tools/pip_package:build_pip_package

**Comment by rodburns** [comment]
For the first error message it looks like you might not have followed all the instructions correctly. I'd suggest cleaning the cache with rm -rf $TMPDIR and making sure all the environment variables are exported before running ./configure. If you post the content of the .tf_configure.bazelrc file generated after running ./configure this would help.

For the second error message, the bazel command is missing some --copt, the full command is:

bazel --output_user_root=$TMPDIR build --config=sycl_arm -c opt --verbose_failures --copt=-DEIGEN_SYCL_LOCAL_THREAD_DIM0=8 --copt=-DEIGEN_SYCL_LOCAL_THREAD_DIM1=8 --copt=-DEIGEN_SYCL_ASYNC_EXECUTION=1 --copt=-Wno-c++11-narrowing //tensorflow/tools/pip_package:build_pip_package

**Comment by eslambakr** [comment]
Here you are the content of the .tf_configure.bazelrc

> build --action_env PYTHON_BIN_PATH="/usr/bin/python"
build --action_env PYTHON_LIB_PATH="/usr/local/lib/python2.7/dist-packages"
build --python_path="/usr/bin/python"
build --define with_jemalloc=true
build:gcp --define with_gcp_support=true
build:hdfs --define with_hdfs_support=true
build:s3 --define with_s3_support=true
build:kafka --define with_kafka_support=true
build:xla --define with_xla_support=true
build:gdr --define with_gdr_support=true
build:verbs --define with_verbs_support=true
build --action_env TF_NEED_OPENCL_SYCL="1"
build --action_env TF_USE_HALF_SYCL="0"
build:sycl --cxxopt=-DTENSORFLOW_SYCL_NO_HALF=1
build --action_env TF_USE_DOUBLE_SYCL="0"
build:sycl --cxxopt=-DTENSORFLOW_SYCL_NO_DOUBLE=1
build --action_env TF_SYCL_USE_LOCAL_MEM="0"
build:sycl --cxxopt=-DNO_LOCAL_MEM
build --action_env TF_SYCL_USE_SERIAL_MEMOP="1"
build --action_env COMPUTECPP_TOOLKIT_PATH="/home/user/ComputeCpp-CE-1.1.3-Ubuntu-16.04-ARM_64"
build --action_env TF_SYCL_BITCODE_TARGET="spir64"
build:sycl --define using_trisycl=false
build --action_env TF_NEED_CUDA="0"
build --action_env TF_DOWNLOAD_CLANG="0"
build --define grpc_no_ares=true
build:opt --copt=-march=armv8-a
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build --strip=always

My error is the same as https://support.codeplay.com/t/tensorflow-build-error/286
Also when I run `${COMPUTECPP_TOOLKIT_PATH}/bin/computecpp_info --dump-version`
It gives me the following error `cannot execute binary file: Exec format error`

Which in fact make sense for me as `file computecpp_info`  outputs the following `computecpp_info: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 3.7.0, BuildID[sha1]=2abb3f359ca68cc3c1087ead2b11477b5c375825, not stripped`

So it makes sense as I am trying to run an executable compiled for an ARM architecture on an x86-64 architecture, but the instructions in the arm tutorial said this commands should be run on the host side not the target.

**Comment by rodburns** [comment]
Ok, can you try a couple of things, we are now in the process of updating our instructions as it seems like they are slightly out of date. Can you try the below? You should clean things up first.

Replace this command:
cp ComputeCpp-CE-${CCPP_VERSION}-Ubuntu-16.04-x86_64/bin/compute++ ComputeCpp-CE-${CCPP_VERSION}-Ubuntu-16.04-ARM_64/bin
with
cp ComputeCpp-CE-${CCPP_VERSION}-Ubuntu-16.04-x86_64/bin/* ComputeCpp-CE-${CCPP_VERSION}-Ubuntu-16.04-ARM_64/bin/

and add this command 
ln -s $HOME/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/lib64/libOpenCL.so $HOME/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/lib/libOpenCL.so

after this command in the instructions
ln -s /usr/include/aarch64-linux-gnu/python2.7/ $HOME/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/include/aarch64-linux-gnu/

**Comment by rodburns** [comment]
We've asked Imagination about their OpenCL drivers and they've confirmed that the current public version isn't compatible with SYCL, but they are investigating when they'll be able to provide such a public driver

What hardware are you planning to run this on, there may be some specific hardware that has been tested with the setup?

**Comment by Rbiessy** [comment]
Since it was mentioned here I just want to point out that we updated the repository and our [instructions](https://developer.codeplay.com/products/computecpp/ce/guides/tensorflow-guide/tensorflow-native-compilation) with PowerVR optimizations.

Thread is inactive so closing.
