### ISSUE TITLE
Is there an example of how to build a custom op with sycl ?

### ISSUE THREAD

**Issue by whatdhack** [codeplaysoftware/tensorflow#29]
### Describe the problem
There appears to be no documentation on how to build a custom op in sycl.

**Comment by Rbiessy** [comment]
You're right we don't have instructions for that. The official guide for [creating an op](https://www.tensorflow.org/guide/create_op) would be a really good place to start. SYCL is not mentioned there but the GPU sections are still relevant.

If you want more details looking at examples in our source code would be my best advice. For instance adding SYCL support to an existing core operation: [bincount_op.cc](https://github.com/codeplaysoftware/tensorflow/blob/master/tensorflow/core/kernels/bincount_op.cc#L224)
Adding an operation in a separate shared library: [ops/topt_engine_op.cc](https://github.com/codeplaysoftware/tensorflow/blob/master/tensorflow/contrib/tensoropt/ops/topt_engine_op.cc#L27) and [kernels/topt_engine_op.cc](https://github.com/codeplaysoftware/tensorflow/blob/master/tensorflow/contrib/tensoropt/kernels/topt_engine_op.cc#L277).

If you need any further help, feel free to ask questions here.
