### ISSUE TITLE
Compile Error: No Such Package

### ISSUE THREAD

**Issue by IceCryptonym** [codeplaysoftware/tensorflow#30]
I have been trying to install this for my AMD GPU but when I try to compile I am getting an error and I'm not sure why.
`ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@grpc//third_party/nanopb': BUILD file not found on package path`

**Comment by Rbiessy** [comment]
Hello, this is indeed curious. Can you confirm to me which version of Bazel are you using? Also have you made any local changes to this repository?

This BUILD file is supposed to be downloaded as part of grpc and can be found in `bazel-tensorflow/external/grpc/third_party/nanopb/BUILD`. Can you find that BUILD file manually? Did Bazel report any other error before the one you posted?

All I can think of is to completely remove the cache and try again. The cache folder is: `realpath $(realpath bazel-tensorflow)/../..`. Let me know how you are getting on with that issue.

**Comment by IceCryptonym** [comment]
The Bazel version I am using is 0.16.0. I did apply a change to the repository for `gettid()` conflict from your comment https://github.com/codeplaysoftware/tensorflow/issues/27#issuecomment-582386964 . Also, there does not seem to be an external folder.

**Comment by Rbiessy** [comment]
Ah alright I understand a bit more the issue then and I was able to reproduce it. Unfortunately I do not see an easy way of fixing this. The proper solution would be pull the changes from upstream and bump our TF version to at least 1.11 I believe. This is not planned at the moment.

Let me remind you that these changes are only needed if you want to use Python 3.7 or more recent. For now I would suggest using Python 3.6 or older.
