### ISSUE TITLE
error name 'http_archive' is not defined while building 

### ISSUE THREAD

**Issue by goodcucumber** [codeplaysoftware/tensorflow#31]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Opensuse 15.2
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 
- **Python version**: 3.6.10
- **Bazel version (if compiling from source)**: 3.3.0
- **GCC/Compiler version (if compiling from source)**: 7.5.0
- **CUDA/cuDNN version**: no
- **GPU model and memory**: Intel HD620 (i7-10710U)
- **Exact command to reproduce**: bazel build --verbose_failures --jobs=6 --config=sycl --config=opt //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
I followed https://developer.codeplay.com/products/computecpp/ce/guides/tensorflow-guide/tensorflow-native-compilation to build tensorflow with sycl, but failed. It gives error "name 'http_archive' is not defined".

### Source code / logs

WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/xxx/tensorflow/tensorflowCL/tensorflow/tools/bazel.rc
ERROR: /home/xxx/tensorflow/tensorflowCL/tensorflow/WORKSPACE:5:1: name 'http_archive' is not defined
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.031s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by Rbiessy** [comment]
Hello, this is a common issue when using a too recent version of bazel as you can see [here](https://github.com/tensorflow/tensorflow/issues/27189).

For our fork of TensorFlow you'll have to downgrade bazel to 0.16.0 as the guide suggests.
